#!/bin/bash


INTERFACE="${BLOCK_INSTANCE:-wlan0}"
ssid=$(iwgetid $INTERFACE -r)

# This script requires sudoers to have passwordless execution.
# To do this, use visudo and add a line like this replacing michael
# with your user name and the path to the script:
# michael ALL=(root) NOPASSWD: /home/michael/dotfiles/wifi.sh
strength_value=$(sudo ~/wifi.sh | grep "$INTERFACE" | awk '{print $3}')
strength=$(echo "$strength_value*10/7" | bc )

echo "$ssid @ $strength%"
